name: bluerandom
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  # sdk: ">=2.16.1 <3.0.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_reactive_ble: ^5.0.2
  location_permissions: ^4.0.1
  flutter_secure_storage: ^8.0.0
  dio: ^5.1.1
  url_launcher: ^6.1.10
  lottie: ^2.3.2
  fluttertoast: ^8.2.1
  shimmer: ^2.0.0
  flutter_riverpod: ^2.3.4
  google_fonts: ^4.0.3
  animated_theme_switcher: ^2.0.8
  syncfusion_flutter_charts: ^21.2.3
  font_awesome_flutter: ^10.4.0
  intl: ^0.18.1
  select_dialog: ^2.0.0
  battery_plus: ^4.0.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
